#!/usr/bin/env python3
"""
Batch translation script for Next.js documentation
Translates front matter and key content sections
"""

import os
import re
import json
from pathlib import Path

def count_files_by_status():
    """Count files by translation status"""
    base_path = Path("D:/code/mycode/next.js-canary/docs")
    target_dirs = ['01-app', '02-pages', '03-architecture', '04-community']

    stats = {
        'total': 0,
        'translated': 0,
        'needs_translation': 0,
        'errors': 0
    }

    files_to_translate = []

    for target_dir in target_dirs:
        dir_path = base_path / target_dir
        if not dir_path.exists():
            continue

        for file_path in dir_path.rglob("*.md*"):
            stats['total'] += 1

            try:
                with open(file_path, 'r', encoding='utf-8') as f:
                    content = f.read()

                # Check if already translated (Chinese in title)
                if re.search(r'^title:\s*[\u4e00-\u9fff]', content, re.MULTILINE):
                    stats['translated'] += 1
                # Check if needs translation (English title)
                elif re.search(r'^title:\s*[a-zA-Z]', content, re.MULTILINE):
                    stats['needs_translation'] += 1
                    files_to_translate.append(str(file_path))
                else:
                    # No title found or other format
                    stats['errors'] += 1

            except Exception as e:
                stats['errors'] += 1
                print(f"Error reading {file_path}: {e}")

    return stats, files_to_translate

def translate_front_matter(content):
    """Translate front matter section"""
    # Common front matter translations
    translations = {
        'title:': 'title:',
        'description:': 'description:',
        'nav_title:': 'nav_title:',
        'related:': 'related:',
        'source:': 'source:',
        'showMetadata:': 'showMetadata:',
        'hideMetadata:': 'hideMetadata:',
    }

    lines = content.split('\n')
    in_front_matter = False
    translated_lines = []

    for line in lines:
        if line.strip() == '---':
            in_front_matter = not in_front_matter
            translated_lines.append(line)
            continue

        if in_front_matter:
            # Handle specific translation cases
            if line.startswith('title: '):
                title_match = re.match(r'title: (.+)', line)
                if title_match:
                    title_text = title_match.group(1)
                    # Skip if already Chinese
                    if re.search(r'[\u4e00-\u9fff]', title_text):
                        translated_lines.append(line)
                    else:
                        # Map common titles
                        title_map = {
                            'Installation': '安装',
                            'Project Structure': '项目结构',
                            'Layouts and Pages': '布局和页面',
                            'Linking and Navigating': '链接和导航',
                            'Server and Client Components': '服务器和客户端组件',
                            'Caching': '缓存',
                            'Fetching Data': '获取数据',
                            'Updating Data': '更新数据',
                            'Error Handling': '错误处理',
                            'CSS': 'CSS',
                            'Images': '图像',
                            'Fonts': '字体',
                            'Metadata': '元数据',
                            'Route Handlers': '路由处理程序',
                            'Deploying': '部署',
                            'Upgrading': '升级',
                            'API Reference': 'API 参考',
                            'Getting Started': '入门指南',
                            'Building Your Application': '构建应用程序',
                            'Configuring': '配置',
                            'Deploying': '部署',
                            'Routing': '路由',
                            'Data Fetching': '数据获取',
                            'Rendering': '渲染',
                            'Caching': '缓存',
                            'Styling': '样式',
                            'Optimizing': '优化',
                            'Testing': '测试',
                            'Authentication': '认证',
                            'Middleware': '中间件',
                            'Internationalization': '国际化',
                            'Environment Variables': '环境变量',
                            'Security': '安全',
                            'Performance': '性能',
                            'Analytics': '分析',
                            'Monitoring': '监控',
                            'Debugging': '调试',
                            'Troubleshooting': '故障排除',
                            'FAQ': '常见问题',
                            'Glossary': '术语表',
                            'Community': '社区',
                            'Contributing': '贡献',
                            'Architecture': '架构',
                            'Supported Browsers': '支持的浏览器',
                            'Turbopack': 'Turbopack',
                            'Webpack': 'Webpack',
                            'TypeScript': 'TypeScript',
                            'ESLint': 'ESLint',
                            'Linting': '代码检查',
                            'Formatting': '代码格式化',
                            'Git': 'Git',
                            'SEO': 'SEO',
                            'PWA': 'PWA',
                            'AMP': 'AMP',
                            'Static Export': '静态导出',
                            'Server Components': '服务器组件',
                            'Client Components': '客户端组件',
                            'Dynamic Routes': '动态路由',
                            'Static Routes': '静态路由',
                            'API Routes': 'API 路由',
                            'Edge Runtime': '边缘运行时',
                            'Node.js Runtime': 'Node.js 运行时',
                            'Streaming': '流式传输',
                            'Suspense': 'Suspense',
                            'Error Boundaries': '错误边界',
                            'Loading States': '加载状态',
                            'Not Found': '未找到',
                            'Redirecting': '重定向',
                            'Rewriting': '重写',
                            'Headers': '请求头',
                            'Cookies': 'Cookie',
                            'Sessions': '会话',
                            'Database': '数据库',
                            'ORM': 'ORM',
                            'Prisma': 'Prisma',
                            'Drizzle': 'Drizzle',
                            'MongoDB': 'MongoDB',
                            'PostgreSQL': 'PostgreSQL',
                            'MySQL': 'MySQL',
                            'SQLite': 'SQLite',
                            'Redis': 'Redis',
                            'Vercel': 'Vercel',
                            'Netlify': 'Netlify',
                            'AWS': 'AWS',
                            'Google Cloud': 'Google Cloud',
                            'Azure': 'Azure',
                            'Docker': 'Docker',
                            'Kubernetes': 'Kubernetes',
                            'CI/CD': 'CI/CD',
                            'GitHub Actions': 'GitHub Actions',
                            'GitLab CI': 'GitLab CI',
                            'Jest': 'Jest',
                            'Cypress': 'Cypress',
                            'Playwright': 'Playwright',
                            'Storybook': 'Storybook',
                            'Figma': 'Figma',
                            'Design': '设计',
                            'UI': 'UI',
                            'UX': 'UX',
                            'Components': '组件',
                            'Props': 'Props',
                            'State': '状态',
                            'Hooks': 'Hooks',
                            'Context': 'Context',
                            'Redux': 'Redux',
                            'Zustand': 'Zustand',
                            'MobX': 'MobX',
                            'Recoil': 'Recoil',
                            'Jotai': 'Jotai',
                            'Valtio': 'Valtio',
                            'React Query': 'React Query',
                            'SWR': 'SWR',
                            'Apollo': 'Apollo',
                            'GraphQL': 'GraphQL',
                            'REST': 'REST',
                            'tRPC': 'tRPC',
                            'WebSocket': 'WebSocket',
                            'SSE': 'SSE',
                            'Fetch': 'Fetch',
                            'Axios': 'Axios',
                            'Node.js': 'Node.js',
                            'Express': 'Express',
                            'Fastify': 'Fastify',
                            'Koa': 'Koa',
                            'Hapi': 'Hapi',
                            'NestJS': 'NestJS',
                            'Remix': 'Remix',
                            'SvelteKit': 'SvelteKit',
                            'Nuxt.js': 'Nuxt.js',
                            'Gatsby': 'Gatsby',
                            'Astro': 'Astro',
                            'Eleventy': 'Eleventy',
                            'Hugo': 'Hugo',
                            'Jekyll': 'Jekyll',
                            'Hexo': 'Hexo',
                            'VuePress': 'VuePress',
                            'Docusaurus': 'Docusaurus',
                            'GitBook': 'GitBook',
                            'Notion': 'Notion',
                            'Confluence': 'Confluence',
                            'Markdown': 'Markdown',
                            'MDX': 'MDX',
                            'LaTeX': 'LaTeX',
                            'Syntax Highlighting': '语法高亮',
                            'Code Blocks': '代码块',
                            'Live Code': '实时代码',
                            'Interactive': '交互式',
                            'Responsive': '响应式',
                            'Mobile': '移动端',
                            'Desktop': '桌面端',
                            'Tablet': '平板',
                            'Accessibility': '无障碍',
                            'A11y': 'A11y',
                            'i18n': 'i18n',
                            'l10n': 'l10n',
                            'RTL': 'RTL',
                            'Dark Mode': '深色模式',
                            'Light Mode': '浅色模式',
                            'Theme': '主题',
                            'Color': '颜色',
                            'Typography': '排版',
                            'Font': '字体',
                            'Icon': '图标',
                            'Image': '图像',
                            'Video': '视频',
                            'Audio': '音频',
                            'Animation': '动画',
                            'Transition': '过渡',
                            'Transform': '变换',
                            'Layout': '布局',
                            'Grid': '网格',
                            'Flexbox': 'Flexbox',
                            'CSS': 'CSS',
                            'Sass': 'Sass',
                            'Less': 'Less',
                            'Stylus': 'Stylus',
                            'PostCSS': 'PostCSS',
                            'Tailwind': 'Tailwind',
                            'Bootstrap': 'Bootstrap',
                            'Bulma': 'Bulma',
                            'Material UI': 'Material UI',
                            'Chakra UI': 'Chakra UI',
                            'Ant Design': 'Ant Design',
                            'Element Plus': 'Element Plus',
                            'Vuetify': 'Vuetify',
                            'Quasar': 'Quasar',
                            'PrimeNG': 'PrimeNG',
                            'NGX Bootstrap': 'NGX Bootstrap',
                            'Clarity': 'Clarity',
                            'Carbon': 'Carbon',
                            'Semantic UI': 'Semantic UI',
                            'Foundation': 'Foundation',
                            'Skeleton': 'Skeleton',
                            'Pure': 'Pure',
                            'Milligram': 'Milligram',
                            'Tachyons': 'Tachyons',
                            'Wing': 'Wing',
                            'Primer': 'Primer',
                            'Base': 'Base',
                            'Spectre': 'Spectre',
                            'Picnic': 'Picnic',
                            'Paper': 'Paper',
                            'Cutestrap': 'Cutestrap',
                            'Mobi.css': 'Mobi.css',
                            'Mini.css': 'Mini.css',
                            'Bulma': 'Bulma',
                            'Buefy': 'Buefy',
                            'Oruga': 'Oruga',
                            'Varlet': 'Varlet',
                            'NutUI': 'NutUI',
                            'Vant': 'Vant',
                            'Mint UI': 'Mint UI',
                            'Cube UI': 'Cube UI',
                            'Mand Mobile': 'Mand Mobile',
                            'Flutter': 'Flutter',
                            'React Native': 'React Native',
                            'Ionic': 'Ionic',
                            'NativeScript': 'NativeScript',
                            'Quasar': 'Quasar',
                            'Framework7': 'Framework7',
                            'Onsen UI': 'Onsen UI',
                            'Monaca': 'Monaca',
                            'Appcelerator': 'Appcelerator',
                            'PhoneGap': 'PhoneGap',
                            'Cordova': 'Cordova',
                            'Capacitor': 'Capacitor',
                            'Electron': 'Electron',
                            'Tauri': 'Tauri',
                            'NW.js': 'NW.js',
                            'Neutralino': 'Neutralino',
                            'Wails': 'Wails',
                            'Fyne': 'Fyne',
                            'Lorca': 'Lorca',
                            'Webview': 'Webview',
                            'GoWalk': 'GoWalk',
                            'Gio': 'Gio',
                            'Bubble Tea': 'Bubble Tea',
                            'Lip Gloss': 'Lip Gloss',
                            'Charm': 'Charm',
                            'VHS': 'VHS',
                            'Glow': 'Glow',
                            'Skate': 'Skate',
                            'Wish': 'Wish',
                            'Bubbles': 'Bubbles',
                            'Progressbar': '进度条',
                            'Spinner': '加载动画',
                            'Loading': '加载中',
                            'Skeleton': '骨架屏',
                            'Empty': '空状态',
                            'Error': '错误',
                            'Success': '成功',
                            'Warning': '警告',
                            'Info': '信息',
                            'Confirm': '确认',
                            'Dialog': '对话框',
                            'Modal': '模态框',
                            'Popup': '弹出框',
                            'Tooltip': '工具提示',
                            'Popover': '弹出提示',
                            'Dropdown': '下拉菜单',
                            'Select': '选择器',
                            'Checkbox': '复选框',
                            'Radio': '单选框',
                            'Switch': '开关',
                            'Slider': '滑块',
                            'Range': '范围',
                            'Input': '输入框',
                            'Textarea': '文本域',
                            'Button': '按钮',
                            'Link': '链接',
                            'Menu': '菜单',
                            'Navigation': '导航',
                            'Breadcrumb': '面包屑',
                            'Pagination': '分页',
                            'Tabs': '标签页',
                            'Steps': '步骤条',
                            'Timeline': '时间线',
                            'Calendar': '日历',
                            'DatePicker': '日期选择器',
                            'TimePicker': '时间选择器',
                            'ColorPicker': '颜色选择器',
                            'FileUpload': '文件上传',
                            'ImageUpload': '图片上传',
                            'Avatar': '头像',
                            'Badge': '徽章',
                            'Tag': '标签',
                            'Progress': '进度',
                            'Rating': '评分',
                            'Slider': '滑块',
                            'Range': '范围',
                            'Knob': '旋钮',
                            'Gauge': '仪表盘',
                            'Chart': '图表',
                            'Graph': '图形',
                            'Table': '表格',
                            'DataGrid': '数据网格',
                            'List': '列表',
                            'Card': '卡片',
                            'Panel': '面板',
                            'Accordion': '手风琴',
                            'Collapse': '折叠面板',
                            'Split': '分割面板',
                            'Drawer': '抽屉',
                            'Sidebar': '侧边栏',
                            'Navbar': '导航栏',
                            'Toolbar': '工具栏',
                            'Footer': '页脚',
                            'Header': '页头',
                            'Layout': '布局',
                            'Grid': '网格',
                            'Flex': '弹性布局',
                            'Container': '容器',
                            'Wrapper': '包装器',
                            'Inner': '内部',
                            'Outer': '外部',
                            'Main': '主要内容',
                            'Aside': '侧边内容',
                            'Section': '区块',
                            'Article': '文章',
                            'Header': '页头',
                            'Footer': '页脚',
                            'Nav': '导航',
                            'Menu': '菜单',
                            'Breadcrumb': '面包屑',
                            'Pagination': '分页',
                            'Search': '搜索',
                            'Filter': '过滤',
                            'Sort': '排序',
                            'Group': '分组',
                            'Aggregate': '聚合',
                            'Calculate': '计算',
                            'Transform': '转换',
                            'Format': '格式化',
                            'Validate': '验证',
                            'Parse': '解析',
                            'Stringify': '序列化',
                            'Serialize': '序列化',
                            'Deserialize': '反序列化',
                            'Encode': '编码',
                            'Decode': '解码',
                            'Hash': '哈希',
                            'Encrypt': '加密',
                            'Decrypt': '解密',
                            'Sign': '签名',
                            'Verify': '验证',
                            'Compress': '压缩',
                            'Decompress': '解压缩',
                            'Zip': '压缩',
                            'Unzip': '解压缩',
                            'Gzip': 'Gzip',
                            'Brotli': 'Brotli',
                            'Deflate': 'Deflate',
                            'Inflate': 'Inflate',
                            'Base64': 'Base64',
                            'Hex': '十六进制',
                            'Binary': '二进制',
                            'Octal': '八进制',
                            'Decimal': '十进制',
                            'Hexadecimal': '十六进制',
                            'ASCII': 'ASCII',
                            'UTF-8': 'UTF-8',
                            'UTF-16': 'UTF-16',
                            'UTF-32': 'UTF-32',
                            'Unicode': 'Unicode',
                            'Locale': '区域设置',
                            'Timezone': '时区',
                            'Currency': '货币',
                            'Number': '数字',
                            'Integer': '整数',
                            'Float': '浮点数',
                            'Double': '双精度',
                            'Boolean': '布尔值',
                            'String': '字符串',
                            'Array': '数组',
                            'Object': '对象',
                            'Function': '函数',
                            'Class': '类',
                            'Interface': '接口',
                            'Type': '类型',
                            'Enum': '枚举',
                            'Union': '联合类型',
                            'Intersection': '交叉类型',
                            'Generic': '泛型',
                            'Template': '模板',
                            'Macro': '宏',
                            'Decorator': '装饰器',
                            'Annotation': '注解',
                            'Attribute': '属性',
                            'Property': '属性',
                            'Field': '字段',
                            'Method': '方法',
                            'Constructor': '构造函数',
                            'Destructor': '析构函数',
                            'Getter': 'Getter',
                            'Setter': 'Setter',
                            'Static': '静态',
                            'Dynamic': '动态',
                            'Public': '公共',
                            'Private': '私有',
                            'Protected': '受保护',
                            'Internal': '内部',
                            'External': '外部',
                            'Abstract': '抽象',
                            'Concrete': '具体',
                            'Virtual': '虚拟',
                            'Override': '重写',
                            'Overload': '重载',
                            'Implement': '实现',
                            'Inherit': '继承',
                            'Extend': '扩展',
                            'Mixin': 'Mixin',
                            'Trait': 'Trait',
                            'Interface': '接口',
                            'Protocol': '协议',
                            'Contract': '契约',
                            'Service': '服务',
                            'Component': '组件',
                            'Module': '模块',
                            'Package': '包',
                            'Library': '库',
                            'Framework': '框架',
                            'Platform': '平台',
                            'Runtime': '运行时',
                            'Environment': '环境',
                            'Context': '上下文',
                            'Scope': '作用域',
                            'Namespace': '命名空间',
                            'Package': '包',
                            'Import': '导入',
                            'Export': '导出',
                            'Require': '引入',
                            'Include': '包含',
                            'Define': '定义',
                            'Declare': '声明',
                            'Initialize': '初始化',
                            'Assign': '赋值',
                            'Reference': '引用',
                            'Pointer': '指针',
                            'Address': '地址',
                            'Memory': '内存',
                            'Stack': '栈',
                            'Heap': '堆',
                            'Register': '寄存器',
                            'Cache': '缓存',
                            'Buffer': '缓冲区',
                            'Queue': '队列',
                            'Stack': '栈',
                            'List': '列表',
                            'Tree': '树',
                            'Graph': '图',
                            'Hash': '哈希',
                            'Map': '映射',
                            'Set': '集合',
                            'Dictionary': '字典',
                            'Array': '数组',
                            'Matrix': '矩阵',
                            'Vector': '向量',
                            'Matrix': '矩阵',
                            'Tensor': '张量',
                            'Algorithm': '算法',
                            'Complexity': '复杂度',
                            'Efficiency': '效率',
                            'Performance': '性能',
                            'Optimization': '优化',
                            'Search': '搜索',
                            'Sort': '排序',
                            'Filter': '过滤',
                            'Transform': '转换',
                            'Reduce': '归约',
                            'Map': '映射',
                            'Iterate': '迭代',
                            'Loop': '循环',
                            'Condition': '条件',
                            'Branch': '分支',
                            'Jump': '跳转',
                            'Call': '调用',
                            'Return': '返回',
                            'Yield': '生成',
                            'Async': '异步',
                            'Await': '等待',
                            'Promise': 'Promise',
                            'Future': 'Future',
                            'Task': '任务',
                            'Thread': '线程',
                            'Process': '进程',
                            'Coroutine': '协程',
                            'Generator': '生成器',
                            'Iterator': '迭代器',
                            'Observer': '观察者',
                            'Observable': '可观察对象',
                            'Stream': '流',
                            'Event': '事件',
                            'Signal': '信号',
                            'Slot': '槽',
                            'Callback': '回调',
                            'Handler': '处理器',
                            'Listener': '监听器',
                            'Emitter': '发射器',
                            'Broadcast': '广播',
                            'Multicast': '多播',
                            'Unicast': '单播',
                            'Anycast': '任播',
                            'Broadcast': '广播',
                            'Publish': '发布',
                            'Subscribe': '订阅',
                            'Notification': '通知',
                            'Message': '消息',
                            'Packet': '数据包',
                            'Frame': '帧',
                            'Segment': '段',
                            'Protocol': '协议',
                            'Standard': '标准',
                            'Specification': '规范',
                            'Documentation': '文档',
                            'Manual': '手册',
                            'Guide': '指南',
                            'Tutorial': '教程',
                            'Course': '课程',
                            'Lesson': '课程',
                            'Exercise': '练习',
                            'Example': '示例',
                            'Demo': '演示',
                            'Sample': '样本',
                            'Template': '模板',
                            'Blueprint': '蓝图',
                            'Scaffold': '脚手架',
                            'Boilerplate': '样板代码',
                            'Snippet': '代码片段',
                            'Fragment': '片段',
                            'Module': '模块',
                            'Component': '组件',
                            'Widget': '小部件',
                            'Plugin': '插件',
                            'Extension': '扩展',
                            'Add-on': '附加组件',
                            'Library': '库',
                            'Package': '包',
                            'Bundle': '包',
                            'Distribution': '发行版',
                            'Release': '发布',
                            'Version': '版本',
                            'Build': '构建',
                            'Compile': '编译',
                            'Link': '链接',
                            'Assemble': '汇编',
                            'Package': '打包',
                            'Deploy': '部署',
                            'Install': '安装',
                            'Uninstall': '卸载',
                            'Update': '更新',
                            'Upgrade': '升级',
                            'Downgrade': '降级',
                            'Rollback': '回滚',
                            'Revert': '还原',
                            'Sync': '同步',
                            'Merge': '合并',
                            'Branch': '分支',
                            'Tag': '标签',
                            'Commit': '提交',
                            'Push': '推送',
                            'Pull': '拉取',
                            'Fetch': '获取',
                            'Clone': '克隆',
                            'Fork': '分叉',
                            'Patch': '补丁',
                            'Diff': '差异',
                            'Conflict': '冲突',
                            'Resolve': '解决',
                            'Ignore': '忽略',
                            'Exclude': '排除',
                            'Include': '包含',
                            'Require': '要求',
                            'Optional': '可选',
                            'Mandatory': '强制',
                            'Required': '必需',
                            'Default': '默认',
                            'Custom': '自定义',
                            'Standard': '标准',
                            'Normal': '正常',
                            'Regular': '常规',
                            'Common': '常见',
                            'Popular': '流行',
                            'Famous': '著名',
                            'Well-known': '知名',
                            'Unknown': '未知',
                            'Hidden': '隐藏',
                            'Visible': '可见',
                            'Transparent': '透明',
                            'Opaque': '不透明',
                            'Clear': '清晰',
                            'Blur': '模糊',
                            'Sharp': '锐利',
                            'Smooth': '平滑',
                            'Rough': '粗糙',
                            'Flat': '平坦',
                            'Round': '圆润',
                            'Square': '方形',
                            'Rectangle': '矩形',
                            'Circle': '圆形',
                            'Triangle': '三角形',
                            'Polygon': '多边形',
                            'Line': '线条',
                            'Curve': '曲线',
                            'Arc': '弧线',
                            'Path': '路径',
                            'Shape': '形状',
                            'Form': '表单',
                            'Size': '大小',
                            'Dimension': '尺寸',
                            'Scale': '比例',
                            'Ratio': '比率',
                            'Proportion': '比例',
                            'Percentage': '百分比',
                            'Unit': '单位',
                            'Measure': '测量',
                            'Calculate': '计算',
                            'Compute': '计算',
                            'Estimate': '估算',
                            'Approximate': '近似',
                            'Exact': '精确',
                            'Accurate': '准确',
                            'Precise': '精确',
                            'Correct': '正确',
                            'Incorrect': '错误',
                            'True': '真',
                            'False': '假',
                            'Yes': '是',
                            'No': '否',
                            'On': '开',
                            'Off': '关',
                            'Enable': '启用',
                            'Disable': '禁用',
                            'Activate': '激活',
                            'Deactivate': '停用',
                            'Start': '开始',
                            'Stop': '停止',
                            'Pause': '暂停',
                            'Resume': '恢复',
                            'Cancel': '取消',
                            'Abort': '中止',
                            'Retry': '重试',
                            'Continue': '继续',
                            'Proceed': '继续',
                            'Skip': '跳过',
                            'Ignore': '忽略',
                            'Accept': '接受',
                            'Reject': '拒绝',
                            'Approve': '批准',
                            'Deny': '拒绝',
                            'Allow': '允许',
                            'Block': '阻止',
                            'Permit': '许可',
                            'Forbid': '禁止',
                            'Grant': '授予',
                            'Revoke': '撤销',
                            'Assign': '分配',
                            'Unassign': '取消分配',
                            'Attach': '附加',
                            'Detach': '分离',
                            'Connect': '连接',
                            'Disconnect': '断开连接',
                            'Join': '加入',
                            'Leave': '离开',
                            'Enter': '进入',
                            'Exit': '退出',
                            'Open': '打开',
                            'Close': '关闭',
                            'Show': '显示',
                            'Hide': '隐藏',
                            'Display': '显示',
                            'Present': '呈现',
                            'Represent': '表示',
                            'Indicate': '指示',
                            'Point': '指向',
                            'Direct': '指向',
                            'Guide': '引导',
                            'Lead': '引导',
                            'Follow': '跟随',
                            'Track': '跟踪',
                            'Trace': '追踪',
                            'Monitor': '监控',
                            'Watch': '观察',
                            'Observe': '观察',
                            'View': '查看',
                            'See': '看到',
                            'Look': '查看',
                            'Find': '查找',
                            'Search': '搜索',
                            'Seek': '寻找',
                            'Locate': '定位',
                            'Position': '位置',
                            'Place': '放置',
                            'Put': '放置',
                            'Set': '设置',
                            'Get': '获取',
                            'Take': '获取',
                            'Receive': '接收',
                            'Send': '发送',
                            'Transmit': '传输',
                            'Transfer': '传输',
                            'Move': '移动',
                            'Copy': '复制',
                            'Paste': '粘贴',
                            'Cut': '剪切',
                            'Delete': '删除',
                            'Remove': '移除',
                            'Clear': '清除',
                            'Clean': '清理',
                            'Empty': '清空',
                            'Fill': '填充',
                            'Load': '加载',
                            'Unload': '卸载',
                            'Import': '导入',
                            'Export': '导出',
                            'Input': '输入',
                            'Output': '输出',
                            'Read': '读取',
                            'Write': '写入',
                            'Save': '保存',
                            'Load': '加载',
                            'Store': '存储',
                            'Retrieve': '检索',
                            'Access': '访问',
                            'Query': '查询',
                            'Update': '更新',
                            'Insert': '插入',
                            'Modify': '修改',
                            'Change': '更改',
                            'Alter': '修改',
                            'Transform': '转换',
                            'Convert': '转换',
                            'Translate': '翻译',
                            'Interpret': '解释',
                            'Compile': '编译',
                            'Assemble': '汇编',
                            'Link': '链接',
                            'Build': '构建',
                            'Package': '打包',
                            'Deploy': '部署',
                            'Install': '安装',
                            'Configure': '配置',
                            'Setup': '设置',
                            'Initialize': '初始化',
                            'Prepare': '准备',
                            'Ready': '就绪',
                            'Available': '可用',
                            'Unavailable': '不可用',
                            'Ready': '就绪',
                            'Busy': '忙碌',
                            'Idle': '空闲',
                            'Active': '活跃',
                            'Inactive': '非活跃',
                            'Online': '在线',
                            'Offline': '离线',
                            'Connected': '已连接',
                            'Disconnected': '已断开连接',
                            'Linked': '已链接',
                            'Unlinked': '未链接',
                            'Bound': '已绑定',
                            'Unbound': '未绑定',
                            'Attached': '已附加',
                            'Detached': '已分离',
                            'Joined': '已加入',
                            'Left': '已离开',
                            'Entered': '已进入',
                            'Exited': '已退出',
                            'Opened': '已打开',
                            'Closed': '已关闭',
                            'Shown': '已显示',
                            'Hidden': '已隐藏',
                            'Displayed': '已显示',
                            'Presented': '已呈现',
                            'Represented': '已表示',
                            'Indicated': '已指示',
                            'Pointed': '已指向',
                            'Directed': '已指向',
                            'Guided': '已引导',
                            'Led': '已引导',
                            'Followed': '已跟随',
                            'Tracked': '已跟踪',
                            'Traced': '已追踪',
                            'Monitored': '已监控',
                            'Watched': '已观察',
                            'Observed': '已观察',
                            'Viewed': '已查看',
                            'Seen': '已看到',
                            'Looked': '已查看',
                            'Found': '已找到',
                            'Searched': '已搜索',
                            'Sought': '已寻找',
                            'Located': '已定位',
                            'Positioned': '已定位',
                            'Placed': '已放置',
                            'Put': '已放置',
                            'Set': '已设置',
                            'Gotten': '已获取',
                            'Taken': '已获取',
                            'Received': '已接收',
                            'Sent': '已发送',
                            'Transmitted': '已传输',
                            'Transferred': '已传输',
                            'Moved': '已移动',
                            'Copied': '已复制',
                            'Pasted': '已粘贴',
                            'Cut': '已剪切',
                            'Deleted': '已删除',
                            'Removed': '已移除',
                            'Cleared': '已清除',
                            'Cleaned': '已清理',
                            'Emptied': '已清空',
                            'Filled': '已填充',
                            'Loaded': '已加载',
                            'Unloaded': '已卸载',
                            'Imported': '已导入',
                            'Exported': '已导出',
                            'Input': '已输入',
                            'Output': '已输出',
                            'Read': '已读取',
                            'Written': '已写入',
                            'Saved': '已保存',
                            'Stored': '已存储',
                            'Retrieved': '已检索',
                            'Accessed': '已访问',
                            'Queried': '已查询',
                            'Updated': '已更新',
                            'Inserted': '已插入',
                            'Modified': '已修改',
                            'Changed': '已更改',
                            'Altered': '已修改',
                            'Transformed': '已转换',
                            'Converted': '已转换',
                            'Translated': '已翻译',
                            'Interpreted': '已解释',
                            'Compiled': '已编译',
                            'Assembled': '已汇编',
                            'Linked': '已链接',
                            'Built': '已构建',
                            'Packaged': '已打包',
                            'Deployed': '已部署',
                            'Installed': '已安装',
                            'Configured': '已配置',
                            'Set up': '已设置',
                            'Initialized': '已初始化',
                            'Prepared': '已准备',
                        }

                        translated_title = title_map.get(title_text, title_text)
                        translated_lines.append(f"title: {translated_title}")
                        break
                    else:
                        translated_lines.append(line)
                        break
            elif line.startswith('description: '):
                # For descriptions, we'll do basic translation
                desc_match = re.match(r'description: (.+)', line)
                if desc_match:
                    desc_text = desc_match.group(1)
                    # Skip if already Chinese
                    if re.search(r'[\u4e00-\u9fff]', desc_text):
                        translated_lines.append(line)
                    else:
                        # Basic description translations
                        desc_map = {
                            'Learn how to': '学习如何',
                            'Learn about': '了解',
                            'Learn more about': '了解更多关于',
                            'API Reference for': 'API 参考 -',
                            'API documentation for': 'API 文档 -',
                            'Documentation for': '文档 -',
                            'Guide to': '指南 -',
                            'Introduction to': '介绍 -',
                            'Overview of': '概述 -',
                            'Understanding': '理解',
                            'Getting Started with': '入门 -',
                            'Building': '构建',
                            'Creating': '创建',
                            'Configuring': '配置',
                            'Using': '使用',
                            'Working with': '使用',
                            'Managing': '管理',
                            'Implementing': '实现',
                            'Deploying': '部署',
                            'Testing': '测试',
                            'Debugging': '调试',
                            'Optimizing': '优化',
                            'Securing': '保护',
                            'Monitoring': '监控',
                            'Troubleshooting': '故障排除',
                            'Best practices for': '最佳实践 -',
                            'Common patterns for': '常见模式 -',
                            'Examples of': '示例 -',
                            'Sample': '示例',
                            'Tutorial': '教程',
                            'Guide': '指南',
                            'Reference': '参考',
                            'Documentation': '文档',
                            'Manual': '手册',
                            'Handbook': '手册',
                            'Cookbook': ' cookbook',
                            'Cheatsheet': '速查表',
                            'Quick start': '快速开始',
                            'Quick reference': '快速参考',
                            'Overview': '概述',
                            'Introduction': '介绍',
                            'Getting started': '入门',
                            'Basic concepts': '基本概念',
                            'Advanced concepts': '高级概念',
                            'Core concepts': '核心概念',
                            'Key concepts': '关键概念',
                            'Fundamentals': '基础知识',
                            'Principles': '原则',
                            'Patterns': '模式',
                            'Best practices': '最佳实践',
                            'Common mistakes': '常见错误',
                            'Pitfalls': '陷阱',
                            'Tips': '技巧',
                            'Tricks': '窍门',
                            'Hints': '提示',
                            'Notes': '注意事项',
                            'Warnings': '警告',
                            'Cautions': '注意事项',
                            'Reminders': '提醒',
                            'Recommendations': '建议',
                            'Suggestions': '建议',
                            'Advice': '建议',
                            'Guidelines': '指导方针',
                            'Rules': '规则',
                            'Conventions': '约定',
                            'Standards': '标准',
                            'Specifications': '规范',
                            'Requirements': '要求',
                            'Prerequisites': '先决条件',
                            'Dependencies': '依赖项',
                            'Dependencies': '依赖',
                            'Setup': '设置',
                            'Configuration': '配置',
                            'Installation': '安装',
                            'Deployment': '部署',
                            'Migration': '迁移',
                            'Upgrade': '升级',
                            'Update': '更新',
                            'Maintenance': '维护',
                            'Support': '支持',
                            'Help': '帮助',
                            'Assistance': '协助',
                            'Resources': '资源',
                            'Tools': '工具',
                            'Utilities': '工具',
                            'Helpers': '辅助工具',
                            'Services': '服务',
                            'Libraries': '库',
                            'Frameworks': '框架',
                            'Platforms': '平台',
                            'Systems': '系统',
                            'Applications': '应用程序',
                            'Programs': '程序',
                            'Scripts': '脚本',
                            'Functions': '函数',
                            'Methods': '方法',
                            'Procedures': '过程',
                            'Processes': '进程',
                            'Tasks': '任务',
                            'Operations': '操作',
                            'Actions': '操作',
                            'Activities': '活动',
                            'Events': '事件',
                            'States': '状态',
                            'Conditions': '条件',
                            'Rules': '规则',
                            'Logic': '逻辑',
                            'Algorithms': '算法',
                            'Data structures': '数据结构',
                            'Variables': '变量',
                            'Constants': '常量',
                            'Parameters': '参数',
                            'Arguments': '参数',
                            'Return values': '返回值',
                            'Results': '结果',
                            'Outputs': '输出',
                            'Inputs': '输入',
                            'Errors': '错误',
                            'Exceptions': '异常',
                            'Warnings': '警告',
                            'Messages': '消息',
                            'Notifications': '通知',
                            'Alerts': '警报',
                            'Logs': '日志',
                            'Reports': '报告',
                            'Summaries': '摘要',
                            'Details': '详细信息',
                            'Information': '信息',
                            'Data': '数据',
                            'Content': '内容',
                            'Files': '文件',
                            'Directories': '目录',
                            'Paths': '路径',
                            'URLs': 'URL',
                            'Links': '链接',
                            'References': '引用',
                            'Sources': '来源',
                            'Resources': '资源',
                            'Assets': '资源',
                            'Media': '媒体',
                            'Images': '图像',
                            'Videos': '视频',
                            'Audio': '音频',
                            'Documents': '文档',
                            'Text': '文本',
                            'Code': '代码',
                            'Markup': '标记',
                            'Styles': '样式',
                            'Scripts': '脚本',
                            'Programs': '程序',
                            'Applications': '应用程序',
                            'Software': '软件',
                            'Hardware': '硬件',
                            'Firmware': '固件',
                            'Systems': '系统',
                            'Networks': '网络',
                            'Databases': '数据库',
                            'Servers': '服务器',
                            'Clients': '客户端',
                            'Services': '服务',
                            'APIs': 'API',
                            'Interfaces': '接口',
                            'Protocols': '协议',
                            'Formats': '格式',
                            'Standards': '标准',
                            'Specifications': '规范',
                            'Documentation': '文档',
                            'Guides': '指南',
                            'Tutorials': '教程',
                            'References': '参考',
                            'Manuals': '手册',
                            'Handbooks': '手册',
                            'Cookbooks': 'cookbook',
                            'Cheatsheets': '速查表',
                            'Quick starts': '快速开始',
                            'Quick references': '快速参考',
                            'Overviews': '概述',
                            'Introductions': '介绍',
                            'Getting started guides': '入门指南',
                            'Basic concepts': '基本概念',
                            'Advanced concepts': '高级概念',
                            'Core concepts': '核心概念',
                            'Key concepts': '关键概念',
                            'Fundamentals': '基础知识',
                            'Principles': '原则',
                            'Patterns': '模式',
                            'Best practices': '最佳实践',
                            'Common mistakes': '常见错误',
                            'Pitfalls': '陷阱',
                            'Tips': '技巧',
                            'Tricks': '窍门',
                            'Hints': '提示',
                            'Notes': '注意事项',
                            'Warnings': '警告',
                            'Cautions': '注意事项',
                            'Reminders': '提醒',
                            'Recommendations': '建议',
                            'Suggestions': '建议',
                            'Advice': '建议',
                            'Guidelines': '指导方针',
                            'Rules': '规则',
                            'Conventions': '约定',
                            'Standards': '标准',
                            'Specifications': '规范',
                            'Requirements': '要求',
                            'Prerequisites': '先决条件',
                            'Dependencies': '依赖项',
                            'Dependencies': '依赖',
                            'Setups': '设置',
                            'Configurations': '配置',
                            'Installations': '安装',
                            'Deployments': '部署',
                            'Migrations': '迁移',
                            'Upgrades': '升级',
                            'Updates': '更新',
                            'Maintenance': '维护',
                            'Support': '支持',
                            'Help': '帮助',
                            'Assistance': '协助',
                            'Resources': '资源',
                            'Tools': '工具',
                            'Utilities': '工具',
                            'Helpers': '辅助工具',
                            'Services': '服务',
                            'Libraries': '库',
                            'Frameworks': '框架',
                            'Platforms': '平台',
                            'Systems': '系统',
                            'Applications': '应用程序',
                            'Programs': '程序',
                            'Scripts': '脚本',
                            'Functions': '函数',
                            'Methods': '方法',
                            'Procedures': '过程',
                            'Processes': '进程',
                            'Tasks': '任务',
                            'Operations': '操作',
                            'Actions': '操作',
                            'Activities': '活动',
                            'Events': '事件',
                            'States': '状态',
                            'Conditions': '条件',
                            'Rules': '规则',
                            'Logic': '逻辑',
                            'Algorithms': '算法',
                            'Data structures': '数据结构',
                            'Variables': '变量',
                            'Constants': '常量',
                            'Parameters': '参数',
                            'Arguments': '参数',
                            'Return values': '返回值',
                            'Results': '结果',
                            'Outputs': '输出',
                            'Inputs': '输入',
                            'Errors': '错误',
                            'Exceptions': '异常',
                            'Warnings': '警告',
                            'Messages': '消息',
                            'Notifications': '通知',
                            'Alerts': '警报',
                            'Logs': '日志',
                            'Reports': '报告',
                            'Summaries': '摘要',
                            'Details': '详细信息',
                            'Information': '信息',
                            'Data': '数据',
                            'Content': '内容',
                            'Files': '文件',
                            'Directories': '目录',
                            'Paths': '路径',
                            'URLs': 'URL',
                            'Links': '链接',
                            'References': '引用',
                            'Sources': '来源',
                            'Resources': '资源',
                            'Assets': '资源',
                            'Media': '媒体',
                            'Images': '图像',
                            'Videos': '视频',
                            'Audio': '音频',
                            'Documents': '文档',
                            'Text': '文本',
                            'Code': '代码',
                            'Markup': '标记',
                            'Styles': '样式',
                            'Scripts': '脚本',
                            'Programs': '程序',
                            'Applications': '应用程序',
                            'Software': '软件',
                            'Hardware': '硬件',
                            'Firmware': '固件',
                            'Systems': '系统',
                            'Networks': '网络',
                            'Databases': '数据库',
                            'Servers': '服务器',
                            'Clients': '客户端',
                            'Services': '服务',
                            'APIs': 'API',
                            'Interfaces': '接口',
                            'Protocols': '协议',
                            'Formats': '格式',
                            'Standards': '标准',
                            'Specifications': '规范',
                            'Documentation': '文档',
                        }

                        # Replace common patterns
                        for eng_pattern, chn_pattern in desc_map.items():
                            if eng_pattern in desc_text:
                                desc_text = desc_text.replace(eng_pattern, chn_pattern)
                                break

                        translated_lines.append(f"description: {desc_text}")
                        break
                    else:
                        translated_lines.append(line)
                        break
            else:
                translated_lines.append(line)
        else:
            translated_lines.append(line)

    return '\n'.join(translated_lines)

def translate_content_basic(content):
    """Basic content translation"""
    # Common section translations
    section_translations = {
        '## Creating a page': '## 创建页面',
        '## Creating a layout': '## 创建布局',
        '## Creating a nested route': '## 创建嵌套路由',
        '## Nesting layouts': '## 嵌套布局',
        '## Creating a dynamic segment': '## 创建动态段',
        '## Rendering with search params': '## 使用搜索参数渲染',
        '## Linking between pages': '## 页面间链接',
        '## Route Props Helpers': '## 路由 Props 辅助类型',
        '### What to use and when': '### 何时使用什么',
        '## Good to know': '## 须知',
        '## System Requirements': '## 系统要求',
        '## Supported Browsers': '## 支持的浏览器',
        '## Using the CLI': '## 使用 CLI',
        '## Manual Installation': '## 手动安装',
        '## Setting up TypeScript': '## 设置 TypeScript',
        '## Setting up Linting': '## 设置代码检查',
        '## Setting up Absolute Imports': '## 设置绝对导入',
        '## Running the Development Server': '## 运行开发服务器',
        '## Creating the `app` directory': '## 创建 `app` 目录',
        '## Creating the `pages` directory': '## 创建 `pages` 目录',
        '## Creating the `public` folder': '## 创建 `public` 文件夹',
        'Next.js uses **file-system based routing**': 'Next.js 使用**基于文件系统的路由**',
        'This page will guide you through': '本页面将指导你',
        'A **page** is UI that is rendered on a specific route': '**页面**是在特定路由上渲染的 UI',
        'A layout is UI that is **shared** between multiple pages': '布局是在多个页面之间**共享**的 UI',
        'On navigation, layouts preserve state': '在导航时，布局保持状态',
        'The layout above is called a **root layout**': '上面的布局被称为**根布局**',
        'The root layout is **required**': '根布局是**必需的**',
        'A nested route is a route composed of multiple URL segments': '嵌套路由是由多个 URL 段组成的路由',
        'By default, layouts in the folder hierarchy are also nested': '默认情况下，文件夹层次结构中的布局也是嵌套的',
        'Dynamic segments allow you to create routes': '动态段允许你创建路由',
        'You can use the `<Link>` component to navigate': '你可以使用 `<Link>` 组件导航',
        '`<Link>` is a built-in Next.js component': '`<Link>` 是一个内置的 Next.js 组件',
        'Next.js exposes utility types': 'Next.js 暴露了实用类型',
    }

    for eng, chn in section_translations.items():
        content = content.replace(eng, chn)

    return content

def process_file(file_path):
    """Process a single file"""
    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Check if already translated
        if re.search(r'^title:\s*[\u4e00-\u9fff]', content, re.MULTILINE):
            return True, "Already translated"

        # Translate front matter
        content = translate_front_matter(content)

        # Basic content translation
        content = translate_content_basic(content)

        # Write back
        with open(file_path, 'w', encoding='utf-8') as f:
            f.write(content)

        return True, "Translated successfully"

    except Exception as e:
        return False, f"Error: {str(e)}"

def main():
    """Main function"""
    print("=== Next.js Documentation Translation Tool ===")
    print("Analyzing files...")

    stats, files_to_translate = count_files_by_status()

    print(f"\nTranslation Statistics:")
    print(f"Total files: {stats['total']}")
    print(f"Already translated: {stats['translated']}")
    print(f"Need translation: {stats['needs_translation']}")
    print(f"Errors: {stats['errors']}")

    if not files_to_translate:
        print("\nNo files need translation!")
        return

    print(f"\nFiles to translate: {len(files_to_translate)}")

    # Process files in batches
    batch_size = 50
    total_processed = 0
    successful = 0
    failed = []

    for i in range(0, len(files_to_translate), batch_size):
        batch = files_to_translate[i:i+batch_size]
        print(f"\nProcessing batch {i//batch_size + 1}/{(len(files_to_translate)-1)//batch_size + 1}")

        for file_path in batch:
            success, message = process_file(file_path)
            total_processed += 1

            if success:
                successful += 1
                print(f"✓ {file_path} - {message}")
            else:
                failed.append((file_path, message))
                print(f"✗ {file_path} - {message}")

            # Progress indicator
            if total_processed % 10 == 0:
                print(f"Progress: {total_processed}/{len(files_to_translate)}")

    # Final summary
    print(f"\n=== Translation Complete ===")
    print(f"Total processed: {total_processed}")
    print(f"Successful: {successful}")
    print(f"Failed: {len(failed)}")

    if failed:
        print("\nFailed files:")
        for file_path, error in failed[:10]:  # Show first 10 failures
            print(f"  - {file_path}: {error}")
        if len(failed) > 10:
            print(f"  ... and {len(failed) - 10} more")

    # Save translation report
    report = {
        'stats': stats,
        'processed': total_processed,
        'successful': successful,
        'failed': len(failed),
        'failed_files': failed
    }

    with open('translation_report.json', 'w', encoding='utf-8') as f:
        json.dump(report, f, ensure_ascii=False, indent=2)

    print(f"\nTranslation report saved to: translation_report.json")

if __name__ == "__main__":
    main()